# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: FSTEAM CYBER
email: fsteamcyber@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hanya sebuah komunitas IT yang tak dikenali banyak orang
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fsteamcyber.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mr614ck
git_repo: mr614ck
github: https://github.com/mr614ck
linkedin: http://linkedin.com/in/fsteamcyber
projects: /projects
mail: mailto:fsteamcyber@gmail.com

include: [_data]

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    hard_wrap: false

theme: minima 
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock

# Jekyll-seo-tag config

social:
  name: FSTEAM CYBER
  links:
    - https://fsteamcyber.github.io

logo: /images/nathan-logo.png
google_analytics: UA-101994139-1
