# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Nathan Lam
email: nathancy@hawaii.edu
description: > # this means to ignore newlines until "baseurl:"
  Nathan Lam. Computer engineering student with a passion for embedded systems, scripting, and clean aesthetic interfaces.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://fsteamcyber.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: nathancy
git_repo: nathancy
github: https://github.com/nathancy
linkedin: http://linkedin.com/in/nathan-lam-14b936112
projects: /projects
mail: mailto:nathancy@hawaii.edu

include: [_data]

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
    input: GFM
    hard_wrap: false

theme: minima 
gems:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-avatar

exclude:
  - Gemfile
  - Gemfile.lock

# Jekyll-seo-tag config

social:
  name: Nathan Lam
  links:
    - https://github.com/nathancy

logo: /images/nathan-logo.png
google_analytics: UA-101994139-1
